require('dotenv').config();
const dns = require('dns');
dns.setServers(['8.8.8.8', '1.1.1.1', '8.8.4.4']);

const mongoose = require('mongoose');

const MONGODB_URI = process.env.MONGODB_URI;
if (!MONGODB_URI) {
  console.error("MONGODB_URI is not defined in env variables!");
  process.exit(1);
}

const entries = [
  {
    date: new Date('2026-06-15'),
    srName: 'SR Shilp',
    recruiterName: 'Meghal Patel',
    candidateName: 'Somil Urmil Shah',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 83,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: 'I spoke with the candidate regarding the reply to the email.',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'SR Shilp',
    recruiterName: 'Meghal Patel',
    candidateName: 'Shiva karan Reddy',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 65,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: 'I spoke with the candidate regarding the current market situation for Financial Analyst positions and discussed the status of their job applications.',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'SR Shilp',
    recruiterName: 'Meghal Patel',
    candidateName: 'Sravani Goud Bushigampala',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 76,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: '',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'SR Shilp',
    recruiterName: 'Meghal Patel',
    candidateName: 'Manvitha Rao',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 0,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: 'I spoke with the candidate regarding the updated resume, new Google Voice number, and LinkedIn profile updates.',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'SR Shilp',
    recruiterName: 'Meghal Patel',
    candidateName: 'Deep Bhagat',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 0,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: '',
    gchatFollowUp: '',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'SR Shilp',
    recruiterName: 'Meghal Patel',
    candidateName: 'Manikanteswar Gandrothula',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 0,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: '',
    gchatFollowUp: '',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'SR Shilp',
    recruiterName: 'Meghal Patel',
    candidateName: 'Sireesha Gangarapu',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 0,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: '',
    gchatFollowUp: '',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'SR Shilp',
    recruiterName: 'Meghal Patel',
    candidateName: 'Pallavi Thorat',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 0,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: '',
    gchatFollowUp: '',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'SR Shilp',
    recruiterName: 'Meghal Patel',
    candidateName: 'Usha Sree Kandulapati',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 0,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: '',
    gchatFollowUp: '',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'SR Shilp',
    recruiterName: 'Dhaval Sathvara',
    candidateName: 'Kshitij Chegondi',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 30,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: '',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'SR Shilp',
    recruiterName: 'Mittal Sharma',
    candidateName: 'Nageshwar Rao Ganta',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 30,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: '',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'SR Shilp',
    recruiterName: 'Dhaval Sathvara',
    candidateName: 'Sai Divya Rayudu',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 41,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: '',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Hinanshi Sukhadiya',
    recruiterName: 'Kunjan  Bhatt',
    candidateName: 'Pranav Sangu',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 81,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: 'Non  for the day',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Hinanshi Sukhadiya',
    recruiterName: 'Kunjan  Bhatt',
    candidateName: 'Dhara Rameshbhai Chandpara',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 158,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: 'talk to her regarding the interview update',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Hinanshi Sukhadiya',
    recruiterName: 'Kunjan  Bhatt',
    candidateName: 'Krishna Charitha Atluri',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 68,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: 'talk to her regarding the interview',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Hinanshi Sukhadiya',
    recruiterName: 'Kunjan  Bhatt',
    candidateName: 'Keerthi Mandaloju',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 106,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: 'talk to her regarding the Ai interviews told her its important to complete the AI interviews',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Hinanshi Sukhadiya',
    recruiterName: 'Kunjan  Bhatt',
    candidateName: 'Nidhi Bomble',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 56,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: 'talk to her regarding the reply in Linkedin messages',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Hinanshi Sukhadiya',
    recruiterName: 'Kunjan Bhatt',
    candidateName: 'Rohit Adike',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 90,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: 'talk him regarding the assessmet',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Hinanshi Sukhadiya',
    recruiterName: 'Hinanshi Sukhadiya',
    candidateName: 'Shreya Dilip Shere',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 81,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: 'No updates yet',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Hinanshi Sukhadiya',
    recruiterName: 'Henil Soni',
    candidateName: 'Sai Sree Ram Maddala',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 44,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: 'Started applying with the new resume',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Hinanshi Sukhadiya',
    recruiterName: 'Brij Gunjal',
    candidateName: 'Shubham Agarwal',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 0,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: 'Got modified resume today and will start application by tomorrow.',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Hinanshi Sukhadiya',
    recruiterName: 'Rajat Limbachiya',
    candidateName: 'Vishwak nunna',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 35,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: 'candidate ask about interviews and marketing related doubts',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Hinanshi Sukhadiya',
    recruiterName: 'Rajat Limbachiya',
    candidateName: 'Naveen panneti',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 16,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: 'Discuss with candidate about linkedin.',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Hinanshi Sukhadiya',
    recruiterName: 'Rajat Limbachiya',
    candidateName: 'Suhith ghanathay',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 20,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: 'told candidate about send followup mail for completed interview',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Hinanshi Sukhadiya',
    recruiterName: 'Rajat Limbachiya',
    candidateName: 'Arun nathi',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 24,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: 'candidate ask about company process,which completed the interviews',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Hinanshi Sukhadiya',
    recruiterName: 'Rajat Limbachiya',
    candidateName: 'Maneeshwar marpu',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 70,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: '',
    gchatFollowUp: '',
    firstCallDone: 'Yes',
    secondFollowUp: '',
    followUpNotes: 'Told candidate to see linkedin message and give reply the one message for next steps.',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Hinanshi Sukhadiya',
    recruiterName: 'Rajat Limbachiya',
    candidateName: 'Bharath kumar mandha',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 64,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: 'Told candidate to open old mail id and reply one mail for interview schedule.',
    firstCallDone: 'Yes',
    secondFollowUp: '',
    followUpNotes: 'Told candidate to open old mail id and reply one mail for interview schedule.',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Hinanshi Sukhadiya',
    recruiterName: 'Rajat Limbachiya',
    candidateName: 'Sravya vemireddy',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 149,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: 'candidate told to see one mail and requested to reply it. and talk about how pass the future interview.',
    firstCallDone: 'Yes',
    secondFollowUp: '',
    followUpNotes: 'candidate told to see one mail and requested to reply it. and talk about how pass the future interview.',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Hinanshi Sukhadiya',
    recruiterName: 'Rajat Limbachiya',
    candidateName: 'Kalesha vali shaik',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 70,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: 'candidate talk about his busy schedule and availability.',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Hinanshi Sukhadiya',
    recruiterName: 'Rajat Limbachiya',
    candidateName: 'Keerthi yetukuri',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 70,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: 'with candidate just talk about how get good response again.',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Barot Himanshu',
    recruiterName: 'Rutu Asodiya',
    candidateName: 'Akshaya Gavhane',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 60,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: 'Regarding resume.',
    firstCallDone: 'Yes',
    secondFollowUp: '',
    followUpNotes: 'Regarding resume.',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Barot Himanshu',
    recruiterName: 'Rutu Asodiya',
    candidateName: 'Shiny Saka',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 85,
    interviewCount: 1,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: 'Regarding interview Feedback.',
    firstCallDone: 'Yes',
    secondFollowUp: '',
    followUpNotes: 'Regarding interview Feedback.',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Barot Himanshu',
    recruiterName: 'Rutu Asodiya',
    candidateName: 'Chandra Adhikari',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 50,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: 'About resume.',
    firstCallDone: 'Yes',
    secondFollowUp: '',
    followUpNotes: 'About resume.',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Barot Himanshu',
    recruiterName: 'Rutu Asodiya',
    candidateName: 'Harshitha Awar',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 60,
    interviewCount: 3,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: 'Regarding interview feedback.',
    firstCallDone: 'Yes',
    secondFollowUp: '',
    followUpNotes: 'Regarding interview feedback.',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Barot Himanshu',
    recruiterName: 'Rutu Asodiya',
    candidateName: 'Chandrasekhar Neelam',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 56,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: 'Regarding resume.',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Barot Himanshu',
    recruiterName: 'Krupal Modi',
    candidateName: 'Sandeep Damodharreddy',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 96,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: 'No Call',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Barot Himanshu',
    recruiterName: 'Krupal Modi',
    candidateName: 'Manogna Tammisetti',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 0,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: '',
    gchatFollowUp: '',
    firstCallDone: '',
    secondFollowUp: 'Chat',
    followUpNotes: 'I shared the newly received assessment with the candidate, and he confirmed that he would complete it and provide an update upon completion. Additionally, he requested a separate resume tailored for the Data Engineer role to support his personal marketing activities. I informed him that I would arrange a new email ID and share the updated Data Engineer resume with him accordingly.',
    targetedProfile: '',
    remarks: 'I shared the newly received assessment with the candidate.'
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Barot Himanshu',
    recruiterName: 'Krupal Modi',
    candidateName: 'Jayanth Reddy',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 40,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: 'I shared the newly received assessment with the candidate, and he confirmed that he would complete it and provide an update upon completion. Additionally, he requested a separate resume tailored for the Data Engineer role to support his personal marketing activities. I informed him that I would arrange a new email ID and share the updated Data Engineer resume with him accordingly.',
    firstCallDone: 'Yes',
    secondFollowUp: '',
    followUpNotes: 'I shared the newly received assessment with the candidate, and he confirmed that he would complete it and provide an update upon completion. Additionally, he requested a separate resume tailored for the Data Engineer role to support his personal marketing activities. I informed him that I would arrange a new email ID and share the updated Data Engineer resume with him accordingly.',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Barot Himanshu',
    recruiterName: 'Krupal Modi',
    candidateName: 'Raviteja Narra',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 0,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: '',
    gchatFollowUp: '',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Barot Himanshu',
    recruiterName: 'Krupal Modi',
    candidateName: 'Ragini Chowdary Kommi',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 0,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: '',
    gchatFollowUp: '',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Barot Himanshu',
    recruiterName: 'Krupal Modi',
    candidateName: 'Shubham Mendapara',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 50,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: 'I reached out to the candidate regarding a required response, and he promptly submitted it. Furthermore, after the updated resume was completed, I shared it with him for verification. He acknowledged receipt and informed me that he would review it and provide an update by tomorrow morning.',
    firstCallDone: 'Yes',
    secondFollowUp: '',
    followUpNotes: 'I reached out to the candidate regarding a required response, and he promptly submitted it. Furthermore, after the updated resume was completed, I shared it with him for verification. He acknowledged receipt and informed me that he would review it and provide an update by tomorrow morning.',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Riyen Sukhadiya',
    recruiterName: 'Pratham Sathavara',
    candidateName: 'Anchal Awasthi',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 0,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: '',
    gchatFollowUp: '',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Riyen Sukhadiya',
    recruiterName: 'Hardik Yogi',
    candidateName: 'Sree Dharani Reddy',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 96,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: 'I Spoke with the candidate about Interview Feedback',
    firstCallDone: 'Yes',
    secondFollowUp: '',
    followUpNotes: 'I Spoke with the candidate about Interview Feedback',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Riyen Sukhadiya',
    recruiterName: 'Hardik Yogi',
    candidateName: 'Madhulika Gangarajula',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 95,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'yes',
    gchatFollowUp: 'I Spoke with the candidate about Application',
    firstCallDone: 'Yes',
    secondFollowUp: '',
    followUpNotes: 'I Spoke with the candidate about Application',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Riyen Sukhadiya',
    recruiterName: 'Hardik Yogi',
    candidateName: 'Abhishek Mule',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 0,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: '',
    gchatFollowUp: '',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Riyen Sukhadiya',
    recruiterName: 'Hardik Yogi',
    candidateName: 'Vibhor Kashmira',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 0,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: '',
    gchatFollowUp: '',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Riyen Sukhadiya',
    recruiterName: 'Hardik Yogi',
    candidateName: 'FNU ADITI',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 0,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: '',
    gchatFollowUp: '',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Riyen Sukhadiya',
    recruiterName: 'Yatri Parmar',
    candidateName: 'Venkat Sai Sri Harsha Tripuraneni',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 0,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: '',
    gchatFollowUp: '',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Riyen Sukhadiya',
    recruiterName: 'Yatri Parmar',
    candidateName: 'Sai Vaishnavi Pratapa',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 87,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: 'Today, I spoke with the candidate regarding the job application process.',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Riyen Sukhadiya',
    recruiterName: 'Yatri Parmar',
    candidateName: 'Vaishnavi Nagu',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 0,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: '',
    gchatFollowUp: '',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Riyen Sukhadiya',
    recruiterName: 'Yatri Parmar',
    candidateName: 'Paul Roweena',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 0,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: '',
    gchatFollowUp: '',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Shekh Mohmadrehan',
    recruiterName: 'Harsh Sadhu',
    candidateName: 'Rohith Arabati',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 70,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: 'Zoom Call :- Candidate was asking me that is there any opportunity...',
    firstCallDone: 'Yes',
    secondFollowUp: 'Call',
    followUpNotes: 'Zoom Call :- I told to candidate to give me some jobs...',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Shekh Mohmadrehan',
    recruiterName: 'Harsh Sadhu',
    candidateName: 'Charmy Darji',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 70,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: 'Zoom Call :- I told to candidate to give me some jobs...',
    firstCallDone: 'Yes',
    secondFollowUp: 'Call',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Shekh Mohmadrehan',
    recruiterName: 'Hardik Vaghela',
    candidateName: 'Divya Chowdary Koripalli',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 63,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: 'I spoke with the candidate. A one-way interview has been received...',
    firstCallDone: 'Yes',
    secondFollowUp: 'Call',
    followUpNotes: 'I spoke with the candidate. A new availability has been received...',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Shekh Mohmadrehan',
    recruiterName: 'Hardik Vaghela',
    candidateName: 'Hema Lalitha Surya Lakshmi Ayaluri',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 47,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: 'I spoke with the candidate. A new availability has been received...',
    firstCallDone: 'Yes',
    secondFollowUp: 'Call',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Shekh Mohmadrehan',
    recruiterName: 'Sakshi Prajapati',
    candidateName: 'Akshaya Mudar',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 40,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: 'Zoom Call :- Candidate was asking about the staffing mail...',
    firstCallDone: 'Yes',
    secondFollowUp: 'Call',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Shekh Mohmadrehan',
    recruiterName: 'Sakshi Prajapati',
    candidateName: 'Yashaswini Sree Neha Garapati',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 0,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: '',
    gchatFollowUp: '',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Shekh Mohmadrehan',
    recruiterName: 'Ajay Parmar',
    candidateName: 'Sathwik Vuppala',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 68,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: 'Today we had a general discussion. I called him, and he directly asked why he is not getting interviews...',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Shekh Mohmadrehan',
    recruiterName: 'Ajay Parmar',
    candidateName: 'Kavya Naidu',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 0,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: '',
    gchatFollowUp: '',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Vishal Suthar',
    recruiterName: 'Vishal Suthar',
    candidateName: 'Dami Gupta',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 40,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'No',
    gchatFollowUp: 'She shared some roles to apply.',
    firstCallDone: 'Yes',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Vishal Suthar',
    recruiterName: 'Aftab Fakir',
    candidateName: 'Pavan Kalam',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 60,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'No',
    gchatFollowUp: 'Called him for RUC session',
    firstCallDone: 'Yes',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Vishal Suthar',
    recruiterName: 'Aftab Fakir',
    candidateName: 'Hamsini Reddy Gunda',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 60,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'No',
    gchatFollowUp: 'No any call today',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Vishal Suthar',
    recruiterName: 'Dax Patel',
    candidateName: 'Deepika Thakur',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 0,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: '',
    gchatFollowUp: '',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Vishal Suthar',
    recruiterName: 'Nitya Soni',
    candidateName: 'Sindhuja Gundla',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 0,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: '',
    gchatFollowUp: '',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Vishal Suthar',
    recruiterName: 'Chintan Raval',
    candidateName: 'Shubhangi Mishra',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 0,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: '',
    gchatFollowUp: '',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'Vishal Suthar',
    recruiterName: 'Chintan Raval',
    candidateName: 'Sohankumar Akki',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 0,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: '',
    gchatFollowUp: '',
    firstCallDone: '',
    secondFollowUp: '',
    followUpNotes: '',
    targetedProfile: '',
    remarks: ''
  },
  {
    date: new Date('2026-06-15'),
    srName: 'SR Shilp',
    recruiterName: 'Hardik Yogi',
    candidateName: 'Sumanth Chada',
    candidateStatus: 'Active',
    longApps: 0,
    shortApps: 0,
    totalApps: 87,
    interviewCount: 0,
    interviewStatus: '',
    interviewDate: null,
    gchat: 'Yes',
    gchatFollowUp: 'N/A',
    firstCallDone: 'Yes',
    secondFollowUp: '',
    followUpNotes: 'N/A',
    targetedProfile: '',
    remarks: ''
  }
];

mongoose.connect(MONGODB_URI, {
  serverSelectionTimeoutMS: 20000,
  connectTimeoutMS: 20000,
  family: 4,
  tls: true,
})
.then(async () => {
  console.log("Connected to MongoDB for seeding recruiter spreadsheet entries...");
  const Recruiter = mongoose.model('Recruiter', new mongoose.Schema({}, { strict: false }));
  
  // Clear any existing entries first to ensure clean import
  await Recruiter.deleteMany({});
  console.log("Cleared recruiters collection.");

  const docs = await Recruiter.insertMany(entries);
  console.log(`Successfully seeded ${docs.length} daily monitoring entries for 15th June 2026!`);
  process.exit(0);
})
.catch(err => {
  console.error("Seeding failed:", err);
  process.exit(1);
});
